name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci 

      - name: Run Cypress tests with retry (Chrome)
        run: |
          attempts=0
          max_attempts=3
          until [ $attempts -ge $max_attempts ]
          do
            npx cypress run --browser chrome && break
            attempts=$((attempts+1))
            echo "Test failed, retrying... ($attempts/$max_attempts)"
            sleep 10
          done

      - name: Upload Failed test screenshots (If test fail)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failed-test-screenshots
          path: cypress/screenshots